# -*- coding: utf-8 -*-
"""mos_ion_monte_correlation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JOLeXxACl1bbHOTOnPSo-pzTqDKrp2aZ
"""

import pandas as pd
from pandas import ExcelWriter
import os
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
os.chdir('/content/drive/My Drive/')

col01 = []
col02 = []


col01.append([0])
col02.append([0])


with open('mos_ion_monte_correlation.lis', "r+") as f:
    data = f.readlines()
    
    for line in data:
      word='ion_nmos='
      if(line.strip().find(word)!=-1):
        col01.append(line[len(word)+1:len(word)+12])

      word='ion_pmos='
      if(line.strip().find(word)!=-1):
        col02.append(line[len(word)+1:len(word)+12])



panda = pd.DataFrame(list(zip(col01,col02)),
              columns=['ion_nmos','ion_pmos'])
panda_sliced = panda.drop(list([0]))

#writer = ExcelWriter('mos_ion_monte.xlsx')
#panda_sliced.to_excel(writer) #can add sheets here if needed
#writer.save()


import numpy
from matplotlib import pyplot



coln01 = numpy.array(col01[1:])
coln02 = numpy.array(col02[1:])
coln01 = coln01.astype('float64') 
coln02 = coln02.astype('float64') 
#allpoints = pd.DataFrame({'x':coln01, 'y':coln02})
#pyplot.scatter(allpoints.x, allpoints.y)
#pyplot.show()
#print(max(coln01))
#print(max(coln02))
#print(coln01.dtype)
corner_nmos = numpy.array([1266, 1266, 1428.3, 1350.8, 1428.3], dtype=float)
corner_pmos = numpy.array([859.66, 967.03, 859.66, 912.07, 967.03], dtype=float)
pyplot.figure(figsize=(12.6, 6.3), dpi=100)
pyplot.scatter(coln01, coln02, c='black', s=10, marker='D')
pyplot.scatter(corner_nmos, corner_pmos, c='red', s=50)
# zip joins x and y coordinates in pairs
i=0
for x,y in zip(corner_nmos,corner_pmos):
    if i==0:
      label="SS"
    elif i==1:
      label="SF"
    elif i==2: 
      label="FS"
    elif i==3: 
      label="TT"
    elif i==4: 
      label="FF"
    # this method is called for each point
    pyplot.annotate(label, # this is the text
                 (x,y), # this is the point to label
                 textcoords="offset points", # how to position the text
                 xytext=(0,5), # distance from text to points (x,y)
                 ha='center', color='red'
                 ) # horizontal alignment can be left, right or center
    i += 1

pyplot.xticks(numpy.arange(1.250e+03, 1.45e+03, 10))
pyplot.yticks(numpy.arange(8.5e+02, 9.8e+02, 10))
pyplot.xlabel("NMOS "+r'$I_D(uA/um)$')
pyplot.ylabel("PMOS "+r'$I_D(uA/um)$')
pyplot.title("Process Variation for PMOS and NMOS\n3-Sigma, NP Correlation = 0.5, MONTE=2500")
pyplot.legend()
pyplot.savefig('mos_ion_monte_cor_0.5.png')
pyplot.show()